# Generated by go2rpm 1
%bcond_without check

# https://github.com/steveyen/gtreap
%global goipath         github.com/steveyen/gtreap
%global commit          0abe01ef9be25c4aedc174758ec2d917314d6d70

%gometa

%global common_description %{expand:
Gtreap is an immutable treap implementation in the Go Language.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Version:        0
Release:        0.1%{?dist}
Summary:        Gtreap is an immutable treap implementation in the Go Language

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Sun Jan 26 03:48:22 CET 2020 Marcel Metz <mmetz@adrian-broher.net> - 0-0.1.20200126git0abe01e
- Initial package
